# Generated by Django 5.2.7 on 2025-10-17 10:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_miles_driving_today', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)], verbose_name='Total Miles Driving Today')),
                ('total_mileage_today', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2000)], verbose_name='Total Mileage Today')),
                ('main_office_address', models.TextField(verbose_name='Main Office Address')),
                ('vehicle_number', models.CharField(max_length=50, verbose_name='Truck/Tractor Number')),
                ('trailer_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Trailer Number')),
                ('home_terminal_address', models.TextField(verbose_name='Home Terminal Address')),
                ('shipping_documents', models.TextField(blank=True, help_text='Enter name of place you regarded and whose collected items work and where each change of duty occurred', null=True, verbose_name='Shipping Documents')),
                ('remarks', models.TextField(blank=True, help_text='Use time standard of former terminal', null=True, verbose_name='Remarks')),
                ('grid_data', models.JSONField(default=dict, help_text='24-hour grid data from 00:00 to 23:00')),
                ('is_certified', models.BooleanField(default=False)),
                ('certified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Name of Carrier')),
                ('driver', models.ForeignKey(limit_choices_to={'user_type': 'driver'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Driver's Daily Log",
                'verbose_name_plural': "Driver's Daily Logs",
                'unique_together': {('driver', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DutyStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='eld.dailylog')),
            ],
        ),
        migrations.CreateModel(
            name='LogCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_signature', models.TextField(verbose_name='Driver Signature')),
                ('certification_date', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('daily_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='eld.dailylog')),
            ],
        ),
    ]
