# Generated by Django 5.2.7 on 2025-10-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalized At'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='from_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='From Location'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='Log Finalized'),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='to_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='To Location'),
        ),
    ]
