# Generated by Django 5.2.7 on 2025-10-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_current_cycle_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityCoordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'city_coordinates',
                'indexes': [models.Index(fields=['city', 'state'], name='city_coordi_city_6ffd5b_idx'), models.Index(fields=['state'], name='city_coordi_state_82d606_idx')],
            },
        ),
    ]
