# Generated by Django 5.2.7 on 2025-10-17 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HOSViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('14_hour', '14-Hour Rule Violation'), ('11_hour', '11-Hour Driving Violation'), ('break', '30-Minute Break Violation'), ('70_hour', '70-Hour/8-Day Violation'), ('sleeper_berth', 'Sleeper Berth Violation')], max_length=20)),
                ('violation_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.driverprofile')),
            ],
        ),
    ]
