# Generated by Django 5.2.7 on 2025-10-17 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hosviolation',
            options={'ordering': ['-violation_time']},
        ),
        migrations.AddField(
            model_name='hosviolation',
            name='break_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hosviolation',
            name='remaining_driving',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hosviolation',
            name='remaining_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hosviolation',
            name='remaining_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hosviolation',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hosviolation',
            name='violation_type',
            field=models.CharField(choices=[('14_hour', 'Violation fenêtre 14 heures'), ('11_hour', 'Violation limite 11 heures conduite'), ('break', 'Violation pause 30 minutes'), ('70_hour', 'Violation cycle 70 heures'), ('14_hour_compliance', 'Conformité 14 heures'), ('11_hour_compliance', 'Conformité 11 heures'), ('70_hour_compliance', 'Conformité 70 heures'), ('break_compliance', 'Conformité pause')], max_length=20),
        ),
    ]
