# Generated by Django 5.2.7 on 2025-10-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hos', '0002_alter_hosviolation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosviolation',
            name='violation_type',
            field=models.CharField(choices=[('14_hour', '14-Hour Rule Violation'), ('11_hour', '11-Hour Driving Violation'), ('break', '30-Minute Break Violation'), ('70_hour', '70-Hour/8-Day Violation'), ('14_hour_compliance', '14-Hour Compliance'), ('11_hour_compliance', '11-Hour Compliance'), ('70_hour_compliance', '70-Hour Compliance'), ('break_compliance', 'Break Compliance')], max_length=20),
        ),
    ]
